name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          response=$(curl -s -o response.json -w "%{http_code}" -X POST https://api.render.com/deploy/$RENDER_SERVICE_ID \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{}')

          if [ "$response" -ne 200 ]; then
            echo "Error: Deploy failed with status code $response"
            exit 1
          fi

          echo "Deploy successful!"